"""update embedding vector size

Revision ID: 8e5e54930572
Revises: 5f1f2e9350c0
Create Date: 2025-06-11 03:35:18.313402

"""
from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision = '8e5e54930572'
down_revision = '5f1f2e9350c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('codechunk', 'embedding',
               existing_type=Vector(dim=768),
               type_=Vector(dim=1536),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('codechunk', 'embedding',
               existing_type=Vector(dim=1536),
               type_=Vector(dim=768),
               existing_nullable=True)
    # ### end Alembic commands ###