"""add index_status enum to repo

Revision ID: f89598ca91e2
Revises: 13ec2aeb883a
Create Date: 2025-06-05 06:06:33.525690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f89598ca91e2'
down_revision = '13ec2aeb883a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE indexstatus AS ENUM ('pending', 'indexing', 'complete')")
    op.add_column('repo', sa.Column('index_status', sa.Enum('pending', 'indexing', 'complete', name='indexstatus'), nullable=False, server_default='pending'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repo', 'index_status')
    op.execute("DROP TYPE indexstatus")
    # ### end Alembic commands ###